# Generated by Django 5.1.1 on 2024-10-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_producto', models.CharField(max_length=100)),
                ('Stock_disponible', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=50)),
                ('Correo_electronico', models.EmailField(max_length=150)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
